# -*- coding: utf-8 -*-
"""AbstractCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlpQz00N0DpCxBPm1Ojn1-oxH0Dc0tWQ
"""

import pandas as pd
import re

# Function to clean the abstract text
def clean_abstract(text):
    if pd.isnull(text):  # Check for NaN values
        return text
    # Remove numerical values and special characters, keeping only letters, spaces, and basic punctuation
    text = re.sub(r'[^a-zA-Z\s.,:;\'"-]', '', text)
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

#from google.colab import files

# Upload the file
#uploaded = files.upload()

# Load the CSV file
input_file = "Abstract.csv"  # Replace with your file path
#output_file = "abstracts_with_keywords.csv"
#df = pd.read_csv(file_path)
ata = pd.read_csv(input_file)
# Apply the cleaning function to the Abstract column
df['Abstract'] = df['Abstract'].apply(clean_abstract)

# Remove rows with missing values in any column
df_cleaned = df.dropna()

# Remove duplicate rows
df_cleaned = df_cleaned.drop_duplicates()

# Save the cleaned DataFrame to a new CSV file
cleaned_file_path = "AbstractsCleanedNew.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned CSV saved to: {cleaned_file_path}")

files.download(cleaned_file_path)

!ls